name: Main

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # Windows
  windowsBuild:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      - name: Installing Libraries
        run: |
          haxelib install lime 8.3.2
          haxelib install openfl 9.5.2
          haxelib install flixel 6.1.2
          haxelib install flixel-addons 4.0.1
          haxelib install flixel-ui 2.6.4
          haxelib install hxcpp 4.3.2
          haxelib install hscript 2.7.0
          haxelib install hxcpp-debug-server
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

      - name: Building
        run: haxelib run lime build windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin
          if-no-files-found: error

  # Linux
  linuxBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      - name: Installing Libraries
        run: |
          haxelib install lime 8.3.2
          haxelib install openfl 9.5.2
          haxelib install flixel 6.1.2
          haxelib install flixel-addons 4.0.1
          haxelib install flixel-ui 2.6.4
          haxelib install hxcpp 4.3.2
          haxelib install hscript 2.7.0
          haxelib install hxcpp-debug-server
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

      - name: Building
        run: haxelib run lime build linux

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxBuild
          path: export/release/linux/bin
          if-no-files-found: error

  # Mac
  macBuild:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      - name: Installing Libraries
        run: |
          haxelib install lime 8.3.2
          haxelib install openfl 9.5.2
          haxelib install flixel 6.1.2
          haxelib install flixel-addons 4.0.1
          haxelib install flixel-ui 2.6.4
          haxelib install hxcpp 4.3.2
          haxelib install hscript 2.7.0
          haxelib install hxcpp-debug-server
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

      - name: Building
        run: haxelib run lime build mac

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macBuild
          path: export/release/macos/bin
          if-no-files-found: error
